var columns = [
    { field: '30_day_storage_cost', header: '30 Day Storage Cost'},
    { field: 'amz_fees_cost', header: 'Amz Fees Cost'},
    { field: 'amz_fulfilment_cost', header: 'Amz Fulfilment Cost'},
    { field: 'bag_cost', header: 'Bag Cost' },
    { field: 'bag_size' , header: 'Bag Size'},
    { field: 'box_cost' , header: 'Box Cost'},
    { field: 'box_type', header: 'Box Type' },
    { field: 'date_added', header: 'Date Added' },
    { field: 'do_we_carry', header: 'Do We Carry?' },
    { field: 'holiday_storage_cost', header: 'Holiday Storage Cost' },
    { field: 'in_shipping_cost', header: 'In-shipping Cost' },
    { field: 'item_cost', header: 'Item Cost'},
    { field: 'item_num', header: 'Item Number'},
    { field: 'labor_cost', header: 'Labor Cost' },
    { field: 'map', header: 'Map' },
    { field: 'meltable', header: 'Meltable?' },
    { field: 'misc_cost', header: 'Misc Cost' },
    { field: 'out_shipping_cost', header: 'Out-shipping Cost' },
    { field: 'price_2021', header: 'Price 2021' },
    { field: 'price_2022', header: 'Price 2022' },
    { field: 'price_2023', header: 'Price 2023' },
    { field: 'process_time_per_unit_sec', header: 'Process Time per Unit Sec' },
    { field: 'total_cost', header: 'Total Cost'},
    { field: 'total_holiday_cost', header: 'Total Holiday Cost' },
    { field: 'vendor', header: 'Vendor' },
    { field: 'weight_lbs', header: 'Weight (Lbs)' },
];