drop extension if exists "pg_net";

alter table "public"."picklist_elements" drop constraint "picklist_elements_recipe_id_fk";

alter table "public"."picklist_elements" drop constraint "picklist_elements_picklist_id_fk";

alter table "public"."requests_to_process" drop constraint "requests_to_process_picklist_id_fkey";

-- Keep existing type to avoid breaking dependent functions during this migration.

drop index if exists "public"."picklist_elements_recipe_id_idx";


  create table "public"."sessions" (
    "session_id" text not null,
    "expires" integer not null,
    "data" text
      );


alter table "public"."cases" add column "invoice_id" bigint;

alter table "public"."picklist_elements" drop column "case_qty";

alter table "public"."picklist_elements" drop column "recipe_id";

alter table "public"."picklist_elements" add column "lane_location" text;

alter table "public"."picklist_elements" add column "request_id" bigint;

alter table "public"."picklist_elements" alter column "picklist_element_id" set generated by default;

alter table "public"."picklist_elements" alter column "picklist_id" set data type bigint using "picklist_id"::bigint;

alter table "public"."picklists" alter column "picklist_id" set generated always;

alter table "public"."profiles" enable row level security;

CREATE INDEX picklist_elements_request_id_idx ON public.picklist_elements USING btree (request_id);

CREATE UNIQUE INDEX sessions_pkey ON public.sessions USING btree (session_id);

alter table "public"."sessions" add constraint "sessions_pkey" PRIMARY KEY using index "sessions_pkey";

alter table "public"."cases" add constraint "cases_invoice_id_fkey" FOREIGN KEY (invoice_id) REFERENCES public.invoices(invoice_id) not valid;

alter table "public"."cases" validate constraint "cases_invoice_id_fkey";

alter table "public"."picklist_elements" add constraint "picklist_elements_request_id_fk" FOREIGN KEY (request_id) REFERENCES public.requests_to_process(request_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."picklist_elements" validate constraint "picklist_elements_request_id_fk";

alter table "public"."picklist_elements" add constraint "picklist_elements_picklist_id_fk" FOREIGN KEY (picklist_id) REFERENCES public.picklists(picklist_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."picklist_elements" validate constraint "picklist_elements_picklist_id_fk";

alter table "public"."requests_to_process" add constraint "requests_to_process_picklist_id_fkey" FOREIGN KEY (picklist_id) REFERENCES public.picklists(picklist_id) not valid;

alter table "public"."requests_to_process" validate constraint "requests_to_process_picklist_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public._get_purchase_order_ids_helper(in_page integer, in_rows_per_page integer, in_filter_field text, in_filter_data text, in_sort_field text, in_sort_order integer)
 RETURNS TABLE(total_count bigint, po_ids bigint[])
 LANGUAGE plpgsql
 STABLE
AS $function$
DECLARE
  v_offset integer := GREATEST((in_page - 1), 0) * GREATEST(in_rows_per_page, 1);
  v_field text := 'purchase_order_id';
  v_sort text := 'ASC';
  v_sql text;
BEGIN
  -- RAISE EXCEPTION 'CHECKING INPUTS IN HELPER - in_page %, in_rows_per_page %, in_filter_field %,  in_filter_data %,  in_sort_field %,  in_sort_order %', in_page, in_rows_per_page, in_filter_field,  in_filter_data,  in_sort_field,  in_sort_order;
  -- normalize sort order
  IF in_sort_order = -1 THEN
    v_sort := 'DESC';
  END IF;

  -- whitelist allowed fields for filter and sort (adjust list as needed)
  IF in_sort_field IN ('purchase_order_id','purchase_order_name','date_ordered','date_received','vendor_id','status') THEN
    v_field := in_sort_field;
  ELSE
    v_field := 'purchase_order_id';
  END IF;

  -- If no filter provided -> simpler path
  IF in_filter_data IS NULL OR btrim(in_filter_data) = '' THEN
    -- total count
    SELECT count(*) INTO total_count FROM purchase_orders;

    -- build SQL to get array of ids in requested order + page
    v_sql := format($f$
      SELECT array_agg(p.purchase_order_id ORDER BY p.%I %s)
      FROM (
        SELECT purchase_order_id
        FROM purchase_orders
        ORDER BY %I %s
        OFFSET $1 LIMIT $2
      ) p
    $f$, v_field, v_sort, v_field, v_sort);

    EXECUTE v_sql USING v_offset, in_rows_per_page INTO po_ids;

      -- RAISE EXCEPTION 'IN HELPER - total count: % and po ids: %', total_count, po_ids;
    RETURN NEXT;
    RETURN;
  END IF;

  RAISE EXCEPTION 'IN HELPER - WENT PAST IF';

  -- Filtered path: count and page with filter. Use parameterized USING for the filter value.
  v_sql := $q$
    SELECT count(*) FROM purchase_orders po
    WHERE (CASE
            WHEN $1 = 'purchase_order_name' THEN po.purchase_order_name ILIKE $2
            WHEN $1 = 'notes' THEN coalesce(po.notes,'') ILIKE $2
            ELSE po.purchase_order_name ILIKE $2 OR coalesce(po.notes,'') ILIKE $2
          END);
  $q$;

EXECUTE v_sql USING in_filter_field, ('%' || in_filter_data || '%') INTO total_count;

  -- Build SQL for paging with filter; note we still use a CASE in WHERE constructed safely by enumerating allowed filter fields
  IF in_filter_field = 'purchase_order_name' THEN
    v_sql := format($f$
      SELECT array_agg(p.purchase_order_id ORDER BY p.%I %s)
      FROM (
        SELECT purchase_order_id
        FROM purchase_orders po
        WHERE po.purchase_order_name ILIKE $1
        ORDER BY %I %s
        OFFSET $2 LIMIT $3
      ) p
    $f$, v_field, v_sort, v_field, v_sort);

    EXECUTE v_sql USING ('%' || in_filter_data || '%'), v_offset, in_rows_per_page INTO po_ids;

  ELSIF in_filter_field = 'notes' THEN
    v_sql := format($f$
      SELECT array_agg(p.purchase_order_id ORDER BY p.%I %s)
      FROM (
        SELECT purchase_order_id
        FROM purchase_orders po
        WHERE coalesce(po.notes,'') ILIKE $1
        ORDER BY %I %s
        OFFSET $2 LIMIT $3
      ) p
    $f$, v_field, v_sort, v_field, v_sort);

    EXECUTE v_sql USING ('%' || in_filter_data || '%'), v_offset, in_rows_per_page INTO po_ids;

  ELSE
    -- default: search both name and notes
    v_sql := format($f$
      SELECT array_agg(p.purchase_order_id ORDER BY p.%I %s)
      FROM (
        SELECT purchase_order_id
        FROM purchase_orders po
        WHERE po.purchase_order_name ILIKE $1 OR coalesce(po.notes,'') ILIKE $1
        ORDER BY %I %s
        OFFSET $2 LIMIT $3
      ) p
    $f$, v_field, v_sort, v_field, v_sort);

    EXECUTE v_sql USING ('%' || in_filter_data || '%'), v_offset, in_rows_per_page INTO po_ids;
  END IF;

  RETURN NEXT;
  RETURN;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.bulk_update_case_v2(case_array jsonb)
 RETURNS text
 LANGUAGE plpgsql
AS $function$
DECLARE
  v_rows_updated integer := 0;
BEGIN
  IF case_array IS NULL OR jsonb_typeof(case_array) <> 'array' THEN
    RAISE EXCEPTION 'case_array must be a JSON array of objects';
  END IF;

  UPDATE cases c
  SET
    units_per_case    = r.units_per_case,
    date_received     = r.date_received,
    notes             = r.notes,
    product_id        = r.product_id,
    location_id       = r.location_id,
    status            = r.status,
    purchase_order_id = r.purchase_order_id,
    request_id        = r.request_id
  FROM jsonb_to_recordset(case_array) AS r(
    case_id bigint,
    units_per_case integer,
    date_received date,
    notes text,
    product_id bigint,
    location_id bigint,
    status text,
    purchase_order_id bigint,
    request_id bigint
  )
  WHERE c.case_id = r.case_id;

  GET DIAGNOSTICS v_rows_updated = ROW_COUNT;

  RETURN format('Boxes/Cases Updated (%s row(s))', v_rows_updated);
END;
$function$
;

CREATE OR REPLACE FUNCTION public.create_picklist(picklist_data jsonb)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
DECLARE
  new_picklist picklists;
  picklist_element JSONB;

BEGIN
  INSERT INTO picklists (label, status) 
  VALUES (
    picklist_data->>'label',
    'Not Picked'
  )
  RETURNING * INTO new_picklist;

  IF new_picklist.picklist_id IS NULL THEN 
    RAISE EXCEPTION 'Error creating picklist record';
  END IF;

  -- RAISE EXCEPTION 'Exception marker 1';

  FOR picklist_element IN SELECT * FROM jsonb_array_elements(picklist_data->'picklistElements') LOOP
    DECLARE
      new_picklist_element picklist_elements;
      linked_case_id bigint;
      request_id_value text;

    BEGIN
      -- RAISE EXCEPTION 'Exception marker 2';
      request_id_value := picklist_element->>'request_id';  -- Get the request_id as text

      -- RAISE EXCEPTION 'Picklist element request id: %', request_id_value;
      UPDATE requests_to_process
      SET picklist_id = new_picklist.picklist_id
      WHERE request_id = request_id_value::bigint;

      -- Check if request_id_value is a valid bigint
      IF request_id_value IS NULL OR request_id_value = '' OR NOT request_id_value ~ '^\d+$' THEN
        RAISE EXCEPTION 'Invalid request_id: %', request_id_value;
      END IF;

      -- RAISE EXCEPTION 'Picklist element data: %', picklist_element;

      INSERT INTO picklist_elements (picklist_id, notes, request_id, lane_location)
      VALUES (
        new_picklist.picklist_id,
        picklist_element->>'notes',
        request_id_value::bigint,
        picklist_element->>'lane_location'
      ) RETURNING * INTO new_picklist_element;

      -- RAISE EXCEPTION 'Exception marker 3';

      FOR linked_case_id IN SELECT * FROM jsonb_array_elements(picklist_element->'usedCaseIds') LOOP
        BEGIN
          UPDATE cases
          SET picklist_element_id = new_picklist_element.picklist_element_id
          WHERE case_id = linked_case_id::bigint;
        END;
      END LOOP;
    END;
  END LOOP;

END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_purchase_orders_with_details(in_page integer, in_rows_per_page integer, in_filter_field text, in_filter_data text, in_sort_field text, in_sort_order integer)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
AS $function$DECLARE
  v_offset integer := GREATEST((in_page - 1), 0) * GREATEST(in_rows_per_page, 1);
  v_po_ids bigint[];
  v_total_count bigint;
  v_result jsonb;
  v_sort_order text;
  test RECORD;
BEGIN
  -- Use helper to get total_count and p.o. ids for this page
  SELECT total_count, po_ids
  INTO v_total_count, v_po_ids
  FROM public._get_purchase_order_ids_helper(in_page, in_rows_per_page, in_filter_field, in_filter_data, in_sort_field, in_sort_order);

  -- RAISE EXCEPTION 'CHECKING IN DETAILS - test: %', test;
  -- RAISE EXCEPTION 'CHECKING IN DETAILS - total count: % and po ids: %', v_total_count, v_po_ids;


  -- If no POs found return empty structure
  IF v_po_ids IS NULL OR array_length(v_po_ids,1) = 0 THEN
    v_result := jsonb_build_object(
      'total_count', COALESCE(v_total_count,0),
      'page', in_page,
      'rows_per_page', in_rows_per_page,
      'purchase_orders', jsonb '[]',
      'all_boxes',           jsonb '[]',
      'all_po_recipes',      jsonb '[]',
      'all_recipes',         jsonb '[]',
      'all_recipe_elements', jsonb '[]',
      'all_products',        jsonb '[]'
    );
    RETURN v_result;
  END IF;

  WITH selected_pos AS (
    SELECT po.*
    FROM purchase_orders po
    WHERE po.purchase_order_id = ANY(v_po_ids)
    ORDER BY array_position(v_po_ids, po.purchase_order_id)
  ),

  -- All cases for these POs with product metadata
  po_cases AS (
    SELECT
      c.*,
      p.product_id   AS product_product_id,
      p.name         AS product_name,
      p.fnsku        AS product_fnsku,
      p.asin         AS product_asin,
      p.item_num     AS product_item_num,
      p.upc          AS product_upc
    FROM cases c
    LEFT JOIN products p ON c.product_id = p.product_id
    WHERE c.purchase_order_id = ANY(v_po_ids)
  ),

  -- Individual boxes (unprocessed cases) per PO as JSON arrays
  individual_boxes_agg AS (
    SELECT
      c.purchase_order_id,
      jsonb_agg(
        jsonb_build_object(
          'case_id', c.case_id,
          'units_per_case', c.units_per_case,
          'date_received', c.date_received,
          'notes', c.notes,
          'product_id', c.product_id,
          'product_name', c.product_name,
          'location_id', c.location_id,
          'status', c.status,
          'purchase_order_id', c.purchase_order_id,
          'request_id', c.request_id,
          'item_num', c.product_item_num,
          'upc', c.product_upc
        ) ORDER BY c.case_id
      ) AS individual_boxes_json
    FROM po_cases c
    WHERE coalesce(nullif(c.product_fnsku,''), nullif(c.product_asin,'')) IS NULL -- unprocessed = boxes
    GROUP BY c.purchase_order_id
  ),

  page_boxes AS (
    SELECT *
    FROM cases
    WHERE purchase_order_id = ANY(v_po_ids) 
  ),

  -- Grouped boxes (unprocessed) per PO
  grouped_boxes AS (
    SELECT
      pb.purchase_order_id,
      jsonb_agg(
        jsonb_build_object(
          'product_id', pb.product_product_id,
          'product_name', pb.product_name,
          'fnsku', pb.product_fnsku,
          'asin', pb.product_asin,
          'item_num', pb.product_item_num,
          'upc', pb.product_upc,
          'amount', pb.cnt,
          'total_units', pb.total_units
        ) ORDER BY pb.product_product_id
      ) AS grouped_boxes_json
    FROM (
      SELECT
        purchase_order_id,
        product_product_id,
        product_name,
        product_fnsku,
        product_asin,
        product_item_num,
        product_upc,
        count(*) AS cnt,
        COALESCE(sum(units_per_case),0) AS total_units
      FROM po_cases
      WHERE coalesce(nullif(product_fnsku,''), nullif(product_asin,'')) IS NULL -- unprocessed
      GROUP BY purchase_order_id, product_product_id, product_name, product_fnsku, product_asin, product_item_num, product_upc
    ) pb
    GROUP BY pb.purchase_order_id
  ),

  -- Grouped cases (processed) per PO
  grouped_cases AS (
    SELECT
      pc.purchase_order_id,
      jsonb_agg(
        jsonb_build_object(
          'product_id', pc.product_product_id,
          'product_name', pc.product_name,
          'fnsku', pc.product_fnsku,
          'asin', pc.product_asin,
          'item_num', pc.product_item_num,
          'upc', pc.product_upc,
          'amount', pc.cnt,
          'total_units', pc.total_units
        ) ORDER BY pc.product_product_id
      ) AS grouped_cases_json
    FROM (
      SELECT
        purchase_order_id,
        product_product_id,
        product_name,
        product_fnsku,
        product_asin,
        product_item_num,
        product_upc,
        count(*) AS cnt,
        COALESCE(sum(units_per_case),0) AS total_units
      FROM po_cases
      WHERE coalesce(nullif(product_fnsku,''), nullif(product_asin,'')) IS NOT NULL -- processed
      GROUP BY purchase_order_id, product_product_id, product_name, product_fnsku, product_asin, product_item_num, product_upc
    ) pc
    GROUP BY pc.purchase_order_id
  ),

  -- po_recipes per PO
  po_recipes_per_po AS (
    SELECT
      pr.purchase_order_id,
      jsonb_agg(to_jsonb(pr) ORDER BY pr.po_recipe_id) AS po_recipes_json,
      array_agg(pr.recipe_id) FILTER (WHERE pr.recipe_id IS NOT NULL) AS recipe_ids
    FROM po_recipes pr
    WHERE pr.purchase_order_id = ANY(v_po_ids)
    GROUP BY pr.purchase_order_id
  ),

  -- recipes referenced by po_recipes for the page (we'll attach per-PO by matching recipe_ids)
  recipes_for_page AS (
    SELECT r.*
    FROM recipes r
    WHERE r.recipe_id IN (
      SELECT DISTINCT recipe_id FROM po_recipes WHERE purchase_order_id = ANY(v_po_ids)
    )
  ),

  -- recipe_elements referenced by those recipes
  recipe_elements_for_page AS (
    SELECT re.*
    FROM recipe_elements re
    WHERE re.recipe_id IN (SELECT recipe_id FROM recipes_for_page)
  ),

  -- Build per-PO recipes and elements JSON by joining recipe ids
  per_po_recipes_json AS (
    SELECT
      p.purchase_order_id,
      COALESCE(p.po_recipes_json, '[]'::jsonb) AS po_recipes_json,
      COALESCE(
        (
          SELECT jsonb_agg(to_jsonb(r) ORDER BY r.recipe_id)
          FROM recipes_for_page r
          WHERE r.recipe_id = ANY(p.recipe_ids)
        ), '[]'::jsonb
      ) AS recipes_json,
      COALESCE(
        (
          SELECT jsonb_agg(to_jsonb(re) ORDER BY re.recipe_element_id)
          FROM recipe_elements_for_page re
          WHERE re.recipe_id = ANY(p.recipe_ids)
        ), '[]'::jsonb
      ) AS recipe_elements_json
    FROM po_recipes_per_po p
  ), 

  all_boxes_agg AS (
        SELECT COALESCE(jsonb_agg(
            jsonb_build_object(
                'case_id',           c.case_id,
                'purchase_order_id', c.purchase_order_id,
                'product_id',        c.product_id,
                'product_name',      c.product_name,
                'units_per_case',    c.units_per_case,
                'status',            c.status,
                'location_id',       c.location_id,
                'request_id',        c.request_id,
                'date_received',     c.date_received,
                'notes',             c.notes,
                'item_num',          c.product_item_num,
                'upc',               c.product_upc
            ) ORDER BY c.case_id
        ), '[]'::jsonb) AS j
        FROM po_cases c
        WHERE COALESCE(NULLIF(c.product_fnsku, ''), NULLIF(c.product_asin, '')) IS NULL
    ),

    -- → this.poRecipes
    all_po_recipes_agg AS (
        SELECT COALESCE(jsonb_agg(
            jsonb_build_object(
                'po_recipe_id',      pr.po_recipe_id,
                'purchase_order_id', pr.purchase_order_id,
                'recipe_id',         pr.recipe_id,
                'qty',               pr.qty
            ) ORDER BY pr.po_recipe_id
        ), '[]'::jsonb) AS j
        FROM po_recipes pr
        WHERE pr.purchase_order_id = ANY(v_po_ids)
    ),

    -- → this.displayRecipes
    all_recipes_agg AS (
        SELECT COALESCE(jsonb_agg(to_jsonb(r) ORDER BY r.recipe_id), '[]'::jsonb) AS j
        FROM recipes_for_page r
    ),

    -- → this.displayRecipeElements
    all_recipe_elements_agg AS (
        SELECT COALESCE(jsonb_agg(to_jsonb(re) ORDER BY re.recipe_element_id), '[]'::jsonb) AS j
        FROM recipe_elements_for_page re
    ),

    -- → this.products
    all_products_agg AS (
        SELECT COALESCE(jsonb_agg(to_jsonb(p) ORDER BY p.product_id), '[]'::jsonb) AS j
        FROM products p
        WHERE p.product_id IN (SELECT DISTINCT product_id FROM po_cases)
           OR p.product_id IN (SELECT DISTINCT product_id FROM recipe_elements_for_page)
    )

  SELECT jsonb_build_object(
    'total_count', v_total_count,
    'page', in_page,
    'rows_per_page', in_rows_per_page,
    'purchase_orders',
      COALESCE(
        jsonb_agg(
          jsonb_build_object(
            'purchase_order_id', sp.purchase_order_id,
            'purchase_order_name', sp.purchase_order_name,
            'vendor_id', sp.vendor_id,
            'date_ordered', sp.date_ordered,
            'date_received', sp.date_received,
            'notes', sp.notes,
            'status', sp.status,
            'discount', sp.discount,
            'vendor_name', v.vendor_name,
            'grouped_cases', COALESCE(gc.grouped_cases_json, '[]'::jsonb),
            'grouped_boxes', COALESCE(gb.grouped_boxes_json, '[]'::jsonb),
            'individual_boxes', COALESCE(ib.individual_boxes_json, '[]'::jsonb),
            'po_recipes', COALESCE(pr.po_recipes_json, '[]'::jsonb),
            'recipes', COALESCE(pr.recipes_json, '[]'::jsonb),
            'recipe_elements', COALESCE(pr.recipe_elements_json, '[]'::jsonb)
          ) ORDER BY array_position(v_po_ids, sp.purchase_order_id)
        ),
        '[]'::jsonb
      ),
    'all_boxes', (SELECT j FROM all_boxes_agg),
    'all_po_recipes', (SELECT j FROM all_po_recipes_agg),
    'all_recipes', (SELECT j FROM all_recipes_agg),
    'all_recipe_elements', (SELECT j FROM all_recipe_elements_agg),
    'all_products', (SELECT j FROM all_products_agg)
  )
  INTO v_result
  FROM selected_pos sp
  LEFT JOIN vendors v ON v.vendor_id = sp.vendor_id
  LEFT JOIN grouped_cases gc ON gc.purchase_order_id = sp.purchase_order_id
  LEFT JOIN grouped_boxes gb ON gb.purchase_order_id = sp.purchase_order_id
  LEFT JOIN individual_boxes_agg ib ON ib.purchase_order_id = sp.purchase_order_id
  LEFT JOIN per_po_recipes_json pr ON pr.purchase_order_id = sp.purchase_order_id;


  RETURN v_result;
END;$function$
;

CREATE OR REPLACE FUNCTION public.get_purchase_orders_with_details_3(in_page integer, in_rows_per_page integer, in_filter_data text)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
AS $function$DECLARE
  v_offset integer := GREATEST((in_page - 1), 0) * GREATEST(in_rows_per_page, 1);
  v_po_ids bigint[];
  v_total_count bigint;
  v_result jsonb;
BEGIN
  -- Normalize filter: if null or empty -> no filter
  IF in_filter_data IS NULL OR btrim(in_filter_data) = '' THEN
    SELECT count(*) INTO v_total_count FROM purchase_orders;
    SELECT array_agg(p.purchase_order_id ORDER BY p.purchase_order_id)
    FROM (
      SELECT purchase_order_id
      FROM purchase_orders
      ORDER BY purchase_order_id
      OFFSET v_offset
      LIMIT in_rows_per_page
    ) p INTO v_po_ids;
  ELSE
    SELECT count(*) INTO v_total_count
    FROM purchase_orders po
    WHERE po.purchase_order_name ILIKE ('%' || in_filter_data || '%')
       OR coalesce(po.notes, '') ILIKE ('%' || in_filter_data || '%');

    SELECT array_agg(p.purchase_order_id ORDER BY p.purchase_order_id)
    FROM (
      SELECT purchase_order_id
      FROM purchase_orders po
      WHERE po.purchase_order_name ILIKE ('%' || in_filter_data || '%')
         OR coalesce(po.notes, '') ILIKE ('%' || in_filter_data || '%')
      ORDER BY po.purchase_order_id
      OFFSET v_offset
      LIMIT in_rows_per_page
    ) p INTO v_po_ids;
  END IF;

  -- If no POs found return empty structure
  IF v_po_ids IS NULL OR array_length(v_po_ids,1) = 0 THEN
    v_result := jsonb_build_object(
      'total_count', COALESCE(v_total_count,0),
      'page', in_page,
      'rows_per_page', in_rows_per_page,
      'purchase_orders', jsonb '[]'
    );
    RETURN v_result;
  END IF;

  WITH selected_pos AS (
    SELECT po.*
    FROM purchase_orders po
    WHERE po.purchase_order_id = ANY(v_po_ids)
    ORDER BY array_position(v_po_ids, po.purchase_order_id)
  ),

  -- All cases for these POs with product metadata
  po_cases AS (
    SELECT
      c.*,
      p.product_id   AS product_product_id,
      p.name         AS product_name,
      p.fnsku        AS product_fnsku,
      p.asin         AS product_asin,
      p.item_num     AS product_item_num,
      p.upc          AS product_upc
    FROM cases c
    LEFT JOIN products p ON c.product_id = p.product_id
    WHERE c.purchase_order_id = ANY(v_po_ids)
  ),

  -- Individual boxes (unprocessed cases) per PO as JSON arrays
  individual_boxes_agg AS (
    SELECT
      c.purchase_order_id,
      jsonb_agg(
        jsonb_build_object(
          'case_id', c.case_id,
          'units_per_case', c.units_per_case,
          'date_received', c.date_received,
          'notes', c.notes,
          'product_id', c.product_id,
          'product_name', c.product_name,
          'location_id', c.location_id,
          'status', c.status,
          'purchase_order_id', c.purchase_order_id,
          'request_id', c.request_id,
          'item_num', c.product_item_num,
          'upc', c.product_upc
        ) ORDER BY c.case_id
      ) AS individual_boxes_json
    FROM po_cases c
    WHERE coalesce(nullif(c.product_fnsku,''), nullif(c.product_asin,'')) IS NULL -- unprocessed = boxes
    GROUP BY c.purchase_order_id
  ),

  -- Grouped boxes (unprocessed) per PO
  grouped_boxes AS (
    SELECT
      pb.purchase_order_id,
      jsonb_agg(
        jsonb_build_object(
          'product_id', pb.product_product_id,
          'product_name', pb.product_name,
          'fnsku', pb.product_fnsku,
          'asin', pb.product_asin,
          'item_num', pb.product_item_num,
          'upc', pb.product_upc,
          'amount', pb.cnt,
          'total_units', pb.total_units
        ) ORDER BY pb.product_product_id
      ) AS grouped_boxes_json
    FROM (
      SELECT
        purchase_order_id,
        product_product_id,
        product_name,
        product_fnsku,
        product_asin,
        product_item_num,
        product_upc,
        count(*) AS cnt,
        COALESCE(sum(units_per_case),0) AS total_units
      FROM po_cases
      WHERE coalesce(nullif(product_fnsku,''), nullif(product_asin,'')) IS NULL -- unprocessed
      GROUP BY purchase_order_id, product_product_id, product_name, product_fnsku, product_asin, product_item_num, product_upc
    ) pb
    GROUP BY pb.purchase_order_id
  ),

  -- Grouped cases (processed) per PO
  grouped_cases AS (
    SELECT
      pc.purchase_order_id,
      jsonb_agg(
        jsonb_build_object(
          'product_id', pc.product_product_id,
          'product_name', pc.product_name,
          'fnsku', pc.product_fnsku,
          'asin', pc.product_asin,
          'item_num', pc.product_item_num,
          'upc', pc.product_upc,
          'amount', pc.cnt,
          'total_units', pc.total_units
        ) ORDER BY pc.product_product_id
      ) AS grouped_cases_json
    FROM (
      SELECT
        purchase_order_id,
        product_product_id,
        product_name,
        product_fnsku,
        product_asin,
        product_item_num,
        product_upc,
        count(*) AS cnt,
        COALESCE(sum(units_per_case),0) AS total_units
      FROM po_cases
      WHERE coalesce(nullif(product_fnsku,''), nullif(product_asin,'')) IS NOT NULL -- processed
      GROUP BY purchase_order_id, product_product_id, product_name, product_fnsku, product_asin, product_item_num, product_upc
    ) pc
    GROUP BY pc.purchase_order_id
  ),

  -- po_recipes per PO
  po_recipes_per_po AS (
    SELECT
      pr.purchase_order_id,
      jsonb_agg(to_jsonb(pr) ORDER BY pr.po_recipe_id) AS po_recipes_json,
      array_agg(pr.recipe_id) FILTER (WHERE pr.recipe_id IS NOT NULL) AS recipe_ids
    FROM po_recipes pr
    WHERE pr.purchase_order_id = ANY(v_po_ids)
    GROUP BY pr.purchase_order_id
  ),

  -- recipes referenced by po_recipes for the page (we'll attach per-PO by matching recipe_ids)
  recipes_for_page AS (
    SELECT r.*
    FROM recipes r
    WHERE r.recipe_id IN (
      SELECT DISTINCT recipe_id FROM po_recipes WHERE purchase_order_id = ANY(v_po_ids)
    )
  ),

  -- recipe_elements referenced by those recipes
  recipe_elements_for_page AS (
    SELECT re.*
    FROM recipe_elements re
    WHERE re.recipe_id IN (SELECT recipe_id FROM recipes_for_page)
  ),

  -- Build per-PO recipes and elements JSON by joining recipe ids
  per_po_recipes_json AS (
    SELECT
      p.purchase_order_id,
      COALESCE(p.po_recipes_json, '[]'::jsonb) AS po_recipes_json,
      COALESCE(
        (
          SELECT jsonb_agg(to_jsonb(r) ORDER BY r.recipe_id)
          FROM recipes_for_page r
          WHERE r.recipe_id = ANY(p.recipe_ids)
        ), '[]'::jsonb
      ) AS recipes_json,
      COALESCE(
        (
          SELECT jsonb_agg(to_jsonb(re) ORDER BY re.recipe_element_id)
          FROM recipe_elements_for_page re
          WHERE re.recipe_id = ANY(p.recipe_ids)
        ), '[]'::jsonb
      ) AS recipe_elements_json
    FROM po_recipes_per_po p
  )

  SELECT jsonb_agg(
    jsonb_build_object(
      'purchase_order_id', sp.purchase_order_id,
      'purchase_order_name', sp.purchase_order_name,
      'vendor_id', sp.vendor_id,
      'date_ordered', sp.date_ordered,
      'date_received', sp.date_received,
      'notes', sp.notes,
      'status', sp.status,
      'discount', sp.discount,
      'vendor_name', v.vendor_name,
      'grouped_cases', COALESCE(gc.grouped_cases_json, '[]'::jsonb),
      'grouped_boxes', COALESCE(gb.grouped_boxes_json, '[]'::jsonb),
      'individual_boxes', COALESCE(ib.individual_boxes_json, '[]'::jsonb),
      'po_recipes', COALESCE(pr.po_recipes_json, '[]'::jsonb),
      'recipes', COALESCE(pr.recipes_json, '[]'::jsonb),
      'recipe_elements', COALESCE(pr.recipe_elements_json, '[]'::jsonb)
    ) ORDER BY array_position(v_po_ids, sp.purchase_order_id)
  ) INTO v_result
  FROM selected_pos sp
  LEFT JOIN vendors v ON v.vendor_id = sp.vendor_id
  LEFT JOIN grouped_cases gc ON gc.purchase_order_id = sp.purchase_order_id
  LEFT JOIN grouped_boxes gb ON gb.purchase_order_id = sp.purchase_order_id
  LEFT JOIN individual_boxes_agg ib ON ib.purchase_order_id = sp.purchase_order_id
  LEFT JOIN per_po_recipes_json pr ON pr.purchase_order_id = sp.purchase_order_id;

  -- Wrap with pagination metadata
  v_result := jsonb_build_object(
    'total_count', v_total_count,
    'page', in_page,
    'rows_per_page', in_rows_per_page,
    'purchase_orders', COALESCE(v_result, '[]'::jsonb)
  );

  RETURN v_result;
END;$function$
;

CREATE OR REPLACE FUNCTION public.get_purchase_orders_with_detailsold(in_page integer, in_rows_per_page integer, in_filter_field text, in_filter_data text, in_sort_field text, in_sort_order integer)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
AS $function$
DECLARE
  v_offset integer := GREATEST((in_page - 1), 0) * GREATEST(in_rows_per_page, 1);
  v_po_ids bigint[];
  v_total_count bigint;
  v_result jsonb;
  v_sort_order text;
BEGIN
  -- Normalize filter: if null or empty -> no filter
  IF in_filter_data IS NULL OR btrim(in_filter_data) = '' THEN
    SELECT count(*) INTO v_total_count FROM purchase_orders;
    SELECT array_agg(p.purchase_order_id ORDER BY p.purchase_order_id)
    FROM (
      SELECT purchase_order_id
      FROM purchase_orders
      ORDER BY purchase_order_id
      OFFSET v_offset
      LIMIT in_rows_per_page
    ) p INTO v_po_ids;
  ELSE
    SELECT count(*) INTO v_total_count
    FROM purchase_orders po
    WHERE po.purchase_order_name ILIKE ('%' || in_filter_data || '%')
       OR coalesce(po.notes, '') ILIKE ('%' || in_filter_data || '%');

    SELECT array_agg(p.purchase_order_id ORDER BY p.purchase_order_id)
    FROM (
      SELECT purchase_order_id
      FROM purchase_orders po
      WHERE po.purchase_order_name ILIKE ('%' || in_filter_data || '%')
         OR coalesce(po.notes, '') ILIKE ('%' || in_filter_data || '%')
      ORDER BY po.purchase_order_id
      OFFSET v_offset
      LIMIT in_rows_per_page
    ) p INTO v_po_ids;
  END IF;

  -- If no POs found return empty structure
  IF v_po_ids IS NULL OR array_length(v_po_ids,1) = 0 THEN
    v_result := jsonb_build_object(
      'total_count', COALESCE(v_total_count,0),
      'page', in_page,
      'rows_per_page', in_rows_per_page,
      'purchase_orders', jsonb '[]'
    );
    RETURN v_result;
  END IF;

  WITH selected_pos AS (
    SELECT po.*
    FROM purchase_orders po
    WHERE po.purchase_order_id = ANY(v_po_ids)
    ORDER BY array_position(v_po_ids, po.purchase_order_id)
  ),

  -- All cases for these POs with product metadata
  po_cases AS (
    SELECT
      c.*,
      p.product_id   AS product_product_id,
      p.name         AS product_name,
      p.fnsku        AS product_fnsku,
      p.asin         AS product_asin,
      p.item_num     AS product_item_num,
      p.upc          AS product_upc
    FROM cases c
    LEFT JOIN products p ON c.product_id = p.product_id
    WHERE c.purchase_order_id = ANY(v_po_ids)
  ),

  -- Individual boxes (unprocessed cases) per PO as JSON arrays
  individual_boxes_agg AS (
    SELECT
      c.purchase_order_id,
      jsonb_agg(
        jsonb_build_object(
          'case_id', c.case_id,
          'units_per_case', c.units_per_case,
          'date_received', c.date_received,
          'notes', c.notes,
          'product_id', c.product_id,
          'product_name', c.product_name,
          'location_id', c.location_id,
          'status', c.status,
          'purchase_order_id', c.purchase_order_id,
          'request_id', c.request_id,
          'item_num', c.product_item_num,
          'upc', c.product_upc
        ) ORDER BY c.case_id
      ) AS individual_boxes_json
    FROM po_cases c
    WHERE coalesce(nullif(c.product_fnsku,''), nullif(c.product_asin,'')) IS NULL -- unprocessed = boxes
    GROUP BY c.purchase_order_id
  ),

  -- Grouped boxes (unprocessed) per PO
  grouped_boxes AS (
    SELECT
      pb.purchase_order_id,
      jsonb_agg(
        jsonb_build_object(
          'product_id', pb.product_product_id,
          'product_name', pb.product_name,
          'fnsku', pb.product_fnsku,
          'asin', pb.product_asin,
          'item_num', pb.product_item_num,
          'upc', pb.product_upc,
          'amount', pb.cnt,
          'total_units', pb.total_units
        ) ORDER BY pb.product_product_id
      ) AS grouped_boxes_json
    FROM (
      SELECT
        purchase_order_id,
        product_product_id,
        product_name,
        product_fnsku,
        product_asin,
        product_item_num,
        product_upc,
        count(*) AS cnt,
        COALESCE(sum(units_per_case),0) AS total_units
      FROM po_cases
      WHERE coalesce(nullif(product_fnsku,''), nullif(product_asin,'')) IS NULL -- unprocessed
      GROUP BY purchase_order_id, product_product_id, product_name, product_fnsku, product_asin, product_item_num, product_upc
    ) pb
    GROUP BY pb.purchase_order_id
  ),

  -- Grouped cases (processed) per PO
  grouped_cases AS (
    SELECT
      pc.purchase_order_id,
      jsonb_agg(
        jsonb_build_object(
          'product_id', pc.product_product_id,
          'product_name', pc.product_name,
          'fnsku', pc.product_fnsku,
          'asin', pc.product_asin,
          'item_num', pc.product_item_num,
          'upc', pc.product_upc,
          'amount', pc.cnt,
          'total_units', pc.total_units
        ) ORDER BY pc.product_product_id
      ) AS grouped_cases_json
    FROM (
      SELECT
        purchase_order_id,
        product_product_id,
        product_name,
        product_fnsku,
        product_asin,
        product_item_num,
        product_upc,
        count(*) AS cnt,
        COALESCE(sum(units_per_case),0) AS total_units
      FROM po_cases
      WHERE coalesce(nullif(product_fnsku,''), nullif(product_asin,'')) IS NOT NULL -- processed
      GROUP BY purchase_order_id, product_product_id, product_name, product_fnsku, product_asin, product_item_num, product_upc
    ) pc
    GROUP BY pc.purchase_order_id
  ),

  -- po_recipes per PO
  po_recipes_per_po AS (
    SELECT
      pr.purchase_order_id,
      jsonb_agg(to_jsonb(pr) ORDER BY pr.po_recipe_id) AS po_recipes_json,
      array_agg(pr.recipe_id) FILTER (WHERE pr.recipe_id IS NOT NULL) AS recipe_ids
    FROM po_recipes pr
    WHERE pr.purchase_order_id = ANY(v_po_ids)
    GROUP BY pr.purchase_order_id
  ),

  -- recipes referenced by po_recipes for the page (we'll attach per-PO by matching recipe_ids)
  recipes_for_page AS (
    SELECT r.*
    FROM recipes r
    WHERE r.recipe_id IN (
      SELECT DISTINCT recipe_id FROM po_recipes WHERE purchase_order_id = ANY(v_po_ids)
    )
  ),

  -- recipe_elements referenced by those recipes
  recipe_elements_for_page AS (
    SELECT re.*
    FROM recipe_elements re
    WHERE re.recipe_id IN (SELECT recipe_id FROM recipes_for_page)
  ),

  -- Build per-PO recipes and elements JSON by joining recipe ids
  per_po_recipes_json AS (
    SELECT
      p.purchase_order_id,
      COALESCE(p.po_recipes_json, '[]'::jsonb) AS po_recipes_json,
      COALESCE(
        (
          SELECT jsonb_agg(to_jsonb(r) ORDER BY r.recipe_id)
          FROM recipes_for_page r
          WHERE r.recipe_id = ANY(p.recipe_ids)
        ), '[]'::jsonb
      ) AS recipes_json,
      COALESCE(
        (
          SELECT jsonb_agg(to_jsonb(re) ORDER BY re.recipe_element_id)
          FROM recipe_elements_for_page re
          WHERE re.recipe_id = ANY(p.recipe_ids)
        ), '[]'::jsonb
      ) AS recipe_elements_json
    FROM po_recipes_per_po p
  )

  SELECT jsonb_agg(
    jsonb_build_object(
      'purchase_order_id', sp.purchase_order_id,
      'purchase_order_name', sp.purchase_order_name,
      'vendor_id', sp.vendor_id,
      'date_ordered', sp.date_ordered,
      'date_received', sp.date_received,
      'notes', sp.notes,
      'status', sp.status,
      'discount', sp.discount,
      'vendor_name', v.vendor_name,
      'grouped_cases', COALESCE(gc.grouped_cases_json, '[]'::jsonb),
      'grouped_boxes', COALESCE(gb.grouped_boxes_json, '[]'::jsonb),
      'individual_boxes', COALESCE(ib.individual_boxes_json, '[]'::jsonb),
      'po_recipes', COALESCE(pr.po_recipes_json, '[]'::jsonb),
      'recipes', COALESCE(pr.recipes_json, '[]'::jsonb),
      'recipe_elements', COALESCE(pr.recipe_elements_json, '[]'::jsonb)
    ) ORDER BY array_position(v_po_ids, sp.purchase_order_id)
  ) INTO v_result
  FROM selected_pos sp
  LEFT JOIN vendors v ON v.vendor_id = sp.vendor_id
  LEFT JOIN grouped_cases gc ON gc.purchase_order_id = sp.purchase_order_id
  LEFT JOIN grouped_boxes gb ON gb.purchase_order_id = sp.purchase_order_id
  LEFT JOIN individual_boxes_agg ib ON ib.purchase_order_id = sp.purchase_order_id
  LEFT JOIN per_po_recipes_json pr ON pr.purchase_order_id = sp.purchase_order_id;

  -- Wrap with pagination metadata
  v_result := jsonb_build_object(
    'total_count', v_total_count,
    'page', in_page,
    'rows_per_page', in_rows_per_page,
    'purchase_orders', COALESCE(v_result, '[]'::jsonb)
  );

  RETURN v_result;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_table_definitions_and_relationships()
 RETURNS TABLE(table_definition text, foreign_key_relationships text, indexes text)
 LANGUAGE plpgsql
AS $function$
DECLARE
    table_rec RECORD;
    fk_rec RECORD;
    index_rec RECORD;
    fk_relationships text;
    index_list text;
BEGIN
    -- Loop through each table in the public schema
    FOR table_rec IN 
        SELECT table_name 
        FROM information_schema.tables 
        WHERE table_schema = 'public' 
        AND table_type = 'BASE TABLE'
    LOOP
        -- Initialize the relationships and indexes for the current table
        fk_relationships := '';
        index_list := '';

        -- Get table definition
        table_definition := format(
            'CREATE TABLE %I ('' || string_agg(column_name || '' '' || 
            CASE WHEN is_nullable = ''NO'' THEN ''NOT NULL'' ELSE '''' END || '' '' || udt_name, '', '') || '');', 
            table_rec.table_name
        );

        -- Get foreign key relationships
        FOR fk_rec IN 
            SELECT 
                kcu.table_name AS child_table,
                kcu.column_name AS child_column,
                ccu.table_name AS parent_table,
                ccu.column_name AS parent_column
            FROM 
                information_schema.table_constraints AS tc
            JOIN 
                information_schema.key_column_usage AS kcu ON tc.constraint_name = kcu.constraint_name
            JOIN 
                information_schema.constraint_column_usage AS ccu ON ccu.constraint_name = tc.constraint_name
            WHERE 
                tc.constraint_type = 'FOREIGN KEY' 
                AND kcu.table_name = table_rec.table_name
        LOOP
            fk_relationships := fk_relationships || format(
                'Foreign Key: %I.%I references %I.%I; ', 
                fk_rec.child_table, 
                fk_rec.child_column, 
                fk_rec.parent_table, 
                fk_rec.parent_column
            );
        END LOOP;

        -- Get indexes
        FOR index_rec IN 
            SELECT 
                indexname, 
                indexdef 
            FROM 
                pg_indexes 
            WHERE 
                tablename = table_rec.table_name
        LOOP
            index_list := index_list || format(
                'Index: %I on %I; ', 
                index_rec.indexname, 
                index_rec.indexdef
            );
        END LOOP;

        -- Return the results for the current table
        RETURN NEXT;
    END LOOP;
END;
$function$
;

-- Type replacement skipped in this migration; handle as a dedicated function/type migration if needed.

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.import_processed_product_keys(product_name text, date_added timestamp with time zone, do_we_carry text, vendor_name text, fnsku text, asin text, default_units_per_case integer, weight_lbs integer, box_type text, box_cost numeric, process_time_per_unit_sec integer, meltable text, products_needed_a text, item_num_a text, qty_1 integer, products_needed_b text, item_num_b text, qty_2 integer, products_needed_c text, item_num_c text, qty_3 integer, products_needed_d text, item_num_d text, qty_4 integer, products_needed_e text, item_num_e text, qty_5 integer, products_needed_f text, item_num_f text, qty_6 integer, bag_cost numeric, in_shipping_cost numeric, out_shipping_cost numeric, labor_cost numeric, item_cost numeric, unit_box_cost numeric, misc_cost numeric, amz_fees_cost numeric, storage_cost_30_day numeric, holiday_storage_cost numeric, total_cost numeric, total_holiday_cost numeric, notes text)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
DECLARE
    current_vendor_name text;
    current_vendor_id bigint;
    added_product_id bigint;
    recipe_label text;
    added_recipe_id bigint;
    product_a_id bigint;
    product_b_id bigint;
    product_c_id bigint;
    product_d_id bigint;
    product_e_id bigint;
    product_f_id bigint;
BEGIN
    -- Split the line into fields (assuming comma-separated values)
    current_vendor_name = vendor_name; -- Adjust index based on your CSV structure

    RAISE LOG 'vendor name: %', vendor_name;

    -- Check if vendor exists
    SELECT v.vendor_id INTO current_vendor_id FROM vendors v WHERE LOWER(v.vendor_name) = LOWER(current_vendor_name);

    -- If vendor does not exist, insert it
    IF current_vendor_id IS NULL THEN
        INSERT INTO vendors (vendor_name) VALUES (current_vendor_name) RETURNING vendor_id INTO current_vendor_id;
    END IF;

    -- Validate required fields before inserting
    IF product_name IS NULL THEN
        RAISE EXCEPTION 'Required fields are missing: product_name: %', product_name;
        RETURN; -- Skip this iteration if required fields are missing
    END IF;

    IF current_vendor_id IS NULL THEN
        RAISE EXCEPTION 'Required fields are missing for product %: current_vendor_id: %', product_name, current_vendor_id;
        RETURN; -- Skip this iteration if required fields are missing
    END IF;

    IF products_needed_a IS NULL THEN 
        RAISE EXCEPTION 'Product % requires at least one input recipe ingredient: products_needed_a: %', product_name, products_needed_a;
        RETURN;
    END IF;

    IF products_needed_a IS NOT NULL AND qty_1 IS NOT NULL THEN 
        SELECT product_id INTO product_a_id FROM product WHERE LOWER(name) = LOWER(products_needed_a);
    END IF;

    IF product_a_id IS NULL THEN 
        RAISE EXCEPTION 'Product % requires at least one input recipe ingredient: products_needed_a: %', product_name, products_needed_a;
        RETURN;
    END IF;

    IF products_needed_b IS NOT NULL AND qty_2 IS NOT NULL THEN 
        SELECT product_id INTO product_b_id FROM product WHERE LOWER(name) = LOWER(products_needed_b);
    END IF;

    IF products_needed_c IS NOT NULL AND qty_3 IS NOT NULL THEN 
        SELECT product_id INTO product_c_id FROM product WHERE LOWER(name) = LOWER(products_needed_c);
    END IF;

    IF products_needed_d IS NOT NULL AND qty_4 IS NOT NULL THEN 
        SELECT product_id INTO product_d_id FROM product WHERE LOWER(name) = LOWER(products_needed_d);
    END IF;

    IF products_needed_e IS NOT NULL AND qty_5 IS NOT NULL THEN 
        SELECT product_id INTO product_e_id FROM product WHERE LOWER(name) = LOWER(products_needed_e);
    END IF;

    IF products_needed_f IS NOT NULL AND qty_6 IS NOT NULL THEN 
        SELECT product_id INTO product_f_id FROM product WHERE LOWER(name) = LOWER(products_needed_f);
    END IF;

    -- Insert the product record (adjust the fields as necessary)
    INSERT INTO products (name, date_added, do_we_carry, vendor_id, fnsku, asin, default_units_per_case, weight_lbs, box_type, box_cost, process_time_per_unit_sec, 
    meltable, bag_cost, in_shipping_cost, out_shipping_cost, labor_cost, item_cost, unit_box_cost, misc_cost, amz_fees_cost, storage_cost_30_day, holiday_storage_cost, total_cost,
    total_holiday_cost, notes) VALUES (
        product_name, -- Product name
        date_added, -- Item number
        do_we_carry, -- Product UPC
        current_vendor_id,
        fnsku, 
        asin, 
        default_units_per_case, 
        weight_lbs, box_type, 
        box_cost, 
        process_time_per_unit_sec, 
        meltable, 
        bag_cost, 
        in_shipping_cost, 
        out_shipping_cost, 
        labor_cost, item_cost, 
        unit_box_cost, misc_cost, 
        amz_fees_cost, 
        storage_cost_30_day, 
        holiday_storage_cost, 
        total_cost,
        total_holiday_cost, 
        notes -- Product key notes
    ) RETURNING product_id INTO added_product_id;

    -- Create recipe based on the products required fields
    recipe_label = format('%s - %s', product_name, fnsku);

    INSERT INTO recipes (label, vendor_id) VALUES (recipe_label, current_vendor_id) RETURNING recipe_id INTO added_recipe_id;

    -- Create a recipe element for the processed product output and however many input elements there are
    INSERT INTO recipe_elements (recipe_id, product_id, type, qty) VALUES (added_recipe_id, added_product_id, 'output', 1);

    IF product_a_id IS NOT NULL THEN
        INSERT INTO recipe_elements (recipe_id, product_id, type, qty) VALUES (added_recipe_id, product_a_id, 'input', qty_1);
    END IF;

    IF product_b_id IS NOT NULL THEN
        INSERT INTO recipe_elements (recipe_id, product_id, type, qty) VALUES (added_recipe_id, product_b_id, 'input', qty_2);
    END IF;

    IF product_c_id IS NOT NULL THEN
        INSERT INTO recipe_elements (recipe_id, product_id, type, qty) VALUES (added_recipe_id, product_c_id, 'input', qty_3);
    END IF;

    IF product_d_id IS NOT NULL THEN
        INSERT INTO recipe_elements (recipe_id, product_id, type, qty) VALUES (added_recipe_id, product_d_id, 'input', qty_4);
    END IF;

    IF product_e_id IS NOT NULL THEN
        INSERT INTO recipe_elements (recipe_id, product_id, type, qty) VALUES (added_recipe_id, product_e_id, 'input', qty_5);
    END IF;

    IF product_f_id IS NOT NULL THEN
        INSERT INTO recipe_elements (recipe_id, product_id, type, qty) VALUES (added_recipe_id, product_f_id, 'input', qty_6);
    END IF;

END;
$function$
;

CREATE OR REPLACE FUNCTION public.name_filter(name_string text, select_function text)
 RETURNS SETOF record
 LANGUAGE plpgsql
AS $function$
DECLARE
    query text;
BEGIN
    -- Construct the dynamic query to execute the select function and filter by name
    query := format('SELECT * FROM %s AS inner_query WHERE inner_query.name ILIKE ''%%'' || %L || ''%%''', select_function, name_string);

    -- Execute the query and return the results
    RETURN QUERY EXECUTE query;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.name_filter_text(name_string text, select_function text)
 RETURNS text[]
 LANGUAGE plpgsql
AS $function$
DECLARE
    query text;
    return_array text[][];
BEGIN
    -- Construct the dynamic query to execute the select function and filter by name
    query := format('SELECT * FROM %s AS inner_query WHERE inner_query.name ILIKE ''%%'' || %L || ''%%''', select_function, name_string);

    -- Execute the query and return the results
    EXECUTE query INTO return_array;
    RETURN return_array;
END;
$function$
;

grant delete on table "public"."sessions" to "anon";

grant insert on table "public"."sessions" to "anon";

grant references on table "public"."sessions" to "anon";

grant select on table "public"."sessions" to "anon";

grant trigger on table "public"."sessions" to "anon";

grant truncate on table "public"."sessions" to "anon";

grant update on table "public"."sessions" to "anon";

grant delete on table "public"."sessions" to "authenticated";

grant insert on table "public"."sessions" to "authenticated";

grant references on table "public"."sessions" to "authenticated";

grant select on table "public"."sessions" to "authenticated";

grant trigger on table "public"."sessions" to "authenticated";

grant truncate on table "public"."sessions" to "authenticated";

grant update on table "public"."sessions" to "authenticated";

grant delete on table "public"."sessions" to "service_role";

grant insert on table "public"."sessions" to "service_role";

grant references on table "public"."sessions" to "service_role";

grant select on table "public"."sessions" to "service_role";

grant trigger on table "public"."sessions" to "service_role";

grant truncate on table "public"."sessions" to "service_role";

grant update on table "public"."sessions" to "service_role";


  create policy "Public profiles are viewable by everyone."
  on "public"."profiles"
  as permissive
  for select
  to public
using (true);



  create policy "Users can insert their own profile."
  on "public"."profiles"
  as permissive
  for insert
  to public
with check ((( SELECT auth.uid() AS uid) = id));



  create policy "Users can update own profile."
  on "public"."profiles"
  as permissive
  for update
  to public
using ((( SELECT auth.uid() AS uid) = id));



